# Generated by Django 4.1.6 on 2023-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_bars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, verbose_name='Почта')),
                ('login', models.CharField(blank=True, max_length=500, verbose_name='Логин')),
                ('surname', models.CharField(blank=True, max_length=500, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Имя')),
                ('password', models.CharField(blank=True, max_length=500, verbose_name='Пароль')),
            ],
        ),
    ]
