# Generated by Django 4.1.7 on 2023-05-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal_bars", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(max_length=50, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="login",
            field=models.CharField(max_length=20, verbose_name="Логин"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="password",
            field=models.CharField(max_length=50, verbose_name="Пароль"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="surname",
            field=models.CharField(max_length=50, verbose_name="Фамилия"),
        ),
    ]
